// <auto-generated />
using Kata.EmployeeReport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kata.EmployeeReport.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200814103444_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("Kata.EmployeeReport.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = (short)21,
                            Name = "Mantas"
                        },
                        new
                        {
                            Id = 2,
                            Age = (short)22,
                            Name = "Rutenis"
                        },
                        new
                        {
                            Id = 3,
                            Age = (short)27,
                            Name = "Aidanas"
                        },
                        new
                        {
                            Id = 4,
                            Age = (short)32,
                            Name = "Arturas"
                        },
                        new
                        {
                            Id = 5,
                            Age = (short)17,
                            Name = "Max"
                        },
                        new
                        {
                            Id = 6,
                            Age = (short)18,
                            Name = "Sepp"
                        },
                        new
                        {
                            Id = 7,
                            Age = (short)15,
                            Name = "Nina"
                        },
                        new
                        {
                            Id = 8,
                            Age = (short)51,
                            Name = "Mike"
                        },
                        new
                        {
                            Id = 9,
                            Age = (short)19,
                            Name = "Lebionka"
                        },
                        new
                        {
                            Id = 10,
                            Age = (short)14,
                            Name = "Artur"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
